### ISSUE TITLE
New accounts are auto-confirmed.

### ISSUE THREAD

**Issue by mmuller** [instedd/guisso#40]
Found in version: 1.1-pre1

Reproduce steps:
Navigate to welcome page of an Instedd tool (resmap-stg, remindem-stg, etc.)
Press 'Create account'
The app redirects to http://login-stg.instedd.org/users/sign_up
There fill the fields
Press 'Sign up'

Obtained:
Guisso redirects to the home page of the Instedd tool and the user is already logged in.
The user doesn't receive a confirmation email.

Expected:
Users should receive a confirmation email.
They have to confirm the account before accessing the Instedd tools.

**Comment by waj** [comment]
This is just a configuration setting (devise_confirmable: true). I just enabled this setting in staging server. It should work just as in production.

**Comment by mmuller** [comment]
It is working as expected.
